apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
      - name: demo
        image: sarahheacock/hello-world-nginx:v2
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  type: LoadBalancer # can automatically create network load balancer
  selector:
    app: my-deployment
  ports:
  - name: demo
    port: 8888
    targetPort: 80
    nodePort: 31000
